INSERT INTO administrative_regions (
  city_code,
  city_name,
  district_name,
  lawd_cd,
  region_level,
  is_active
) VALUES
  ('seoul', '서울특별시', '종로구', '11110', 'district', 1),
  ('seoul', '서울특별시', '중구', '11140', 'district', 1),
  ('seoul', '서울특별시', '용산구', '11170', 'district', 1),
  ('seoul', '서울특별시', '성동구', '11200', 'district', 1),
  ('seoul', '서울특별시', '광진구', '11215', 'district', 1),
  ('seoul', '서울특별시', '동대문구', '11230', 'district', 1),
  ('seoul', '서울특별시', '중랑구', '11260', 'district', 1),
  ('seoul', '서울특별시', '성북구', '11290', 'district', 1),
  ('seoul', '서울특별시', '강북구', '11305', 'district', 1),
  ('seoul', '서울특별시', '도봉구', '11320', 'district', 1),
  ('seoul', '서울특별시', '노원구', '11350', 'district', 1),
  ('seoul', '서울특별시', '은평구', '11380', 'district', 1),
  ('seoul', '서울특별시', '서대문구', '11410', 'district', 1),
  ('seoul', '서울특별시', '마포구', '11440', 'district', 1),
  ('seoul', '서울특별시', '양천구', '11470', 'district', 1),
  ('seoul', '서울특별시', '강서구', '11500', 'district', 1),
  ('seoul', '서울특별시', '구로구', '11530', 'district', 1),
  ('seoul', '서울특별시', '금천구', '11545', 'district', 1),
  ('seoul', '서울특별시', '영등포구', '11560', 'district', 1),
  ('seoul', '서울특별시', '동작구', '11590', 'district', 1),
  ('seoul', '서울특별시', '관악구', '11620', 'district', 1),
  ('seoul', '서울특별시', '서초구', '11650', 'district', 1),
  ('seoul', '서울특별시', '강남구', '11680', 'district', 1),
  ('seoul', '서울특별시', '송파구', '11710', 'district', 1),
  ('seoul', '서울특별시', '강동구', '11740', 'district', 1),
  ('busan', '부산광역시', '중구', '26110', 'district', 1),
  ('busan', '부산광역시', '서구', '26140', 'district', 1),
  ('busan', '부산광역시', '동구', '26170', 'district', 1),
  ('busan', '부산광역시', '영도구', '26200', 'district', 1),
  ('busan', '부산광역시', '부산진구', '26230', 'district', 1),
  ('busan', '부산광역시', '동래구', '26260', 'district', 1),
  ('busan', '부산광역시', '남구', '26290', 'district', 1),
  ('busan', '부산광역시', '북구', '26320', 'district', 1),
  ('busan', '부산광역시', '해운대구', '26350', 'district', 1),
  ('busan', '부산광역시', '사하구', '26380', 'district', 1),
  ('busan', '부산광역시', '금정구', '26410', 'district', 1),
  ('busan', '부산광역시', '강서구', '26440', 'district', 1),
  ('busan', '부산광역시', '연제구', '26470', 'district', 1),
  ('busan', '부산광역시', '수영구', '26500', 'district', 1),
  ('busan', '부산광역시', '사상구', '26530', 'district', 1),
  ('busan', '부산광역시', '기장군', '26710', 'district', 1)
ON DUPLICATE KEY UPDATE
  city_code = VALUES(city_code),
  city_name = VALUES(city_name),
  district_name = VALUES(district_name),
  region_level = VALUES(region_level),
  is_active = VALUES(is_active);
